name: Build Vue and publish pages artifact
permissions:
  id-token: write
  pages: write
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Publish
      run: bun build-only
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4
